language: java

jdk:
  - openjdk14

sudo: false


env:
  global:
    - CODECOV_TOKEN="f78e5a93-4610-4948-a3f5-041acafc421e"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - langua095@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

    script:
      - mvn test -B